import './header/header';
import './mobile-menu/mobMenu';
import './about-me/accordion';
import './about-me/swipper';
import './work-together/work-together';
import './reviews/reviews';
import './faq/faq';
import './projects/projects';
import './covers/covers';
